# Generated by Django 4.1.2 on 2022-10-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='advocate_years_exp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
