# Generated by Django 4.1.2 on 2022-10-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocate', '0002_alter_advocate_advocate_years_exp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='advocate',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
