# Generated by Django 4.1.2 on 2022-10-17 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advocate', '0003_alter_company_options_advocate_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='advocate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL),
        ),
    ]
