# Generated by Django 4.1.2 on 2022-10-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advocate', '0005_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='advocate',
            new_name='advocator',
        ),
    ]
