# Generated by Django 4.1.2 on 2022-10-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advocate', '0006_rename_advocate_review_advocator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('advocator', 'reviewed_by')},
        ),
    ]
